// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: internal/driver/proto/restaurant_type.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RestaurantTypeServiceClient is the client API for RestaurantTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantTypeServiceClient interface {
	GetRestaurantTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetRestaurantTypeResponse, error)
}

type restaurantTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantTypeServiceClient(cc grpc.ClientConnInterface) RestaurantTypeServiceClient {
	return &restaurantTypeServiceClient{cc}
}

func (c *restaurantTypeServiceClient) GetRestaurantTypes(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetRestaurantTypeResponse, error) {
	out := new(GetRestaurantTypeResponse)
	err := c.cc.Invoke(ctx, "/RestaurantTypeService/GetRestaurantTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantTypeServiceServer is the server API for RestaurantTypeService service.
// All implementations must embed UnimplementedRestaurantTypeServiceServer
// for forward compatibility
type RestaurantTypeServiceServer interface {
	GetRestaurantTypes(context.Context, *emptypb.Empty) (*GetRestaurantTypeResponse, error)
	mustEmbedUnimplementedRestaurantTypeServiceServer()
}

// UnimplementedRestaurantTypeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRestaurantTypeServiceServer struct {
}

func (UnimplementedRestaurantTypeServiceServer) GetRestaurantTypes(context.Context, *emptypb.Empty) (*GetRestaurantTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurantTypes not implemented")
}
func (UnimplementedRestaurantTypeServiceServer) mustEmbedUnimplementedRestaurantTypeServiceServer() {}

// UnsafeRestaurantTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantTypeServiceServer will
// result in compilation errors.
type UnsafeRestaurantTypeServiceServer interface {
	mustEmbedUnimplementedRestaurantTypeServiceServer()
}

func RegisterRestaurantTypeServiceServer(s grpc.ServiceRegistrar, srv RestaurantTypeServiceServer) {
	s.RegisterService(&RestaurantTypeService_ServiceDesc, srv)
}

func _RestaurantTypeService_GetRestaurantTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantTypeServiceServer).GetRestaurantTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RestaurantTypeService/GetRestaurantTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantTypeServiceServer).GetRestaurantTypes(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantTypeService_ServiceDesc is the grpc.ServiceDesc for RestaurantTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RestaurantTypeService",
	HandlerType: (*RestaurantTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRestaurantTypes",
			Handler:    _RestaurantTypeService_GetRestaurantTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/driver/proto/restaurant_type.proto",
}
