version: "3.8"
services:
  db:
    image: postgres:14.8-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
